services:
  postgresql:
    image: ${POSTGRESQL_IMAGE}
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - defos_data:/bitnami/postgresql:rw
    ports:
      - ${POSTGRESQL_PORTS}
    networks:
      - defos_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  defos_data:
    driver: local

networks:
  defos_network:
    driver: bridge